name: torch3.7
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20210324.1=h0e60522_0
  - arrow-cpp=4.0.0=py37hb1a8454_3_cpu
  - aws-c-cal=0.5.11=he19cf47_0
  - aws-c-common=0.6.2=h8ffe710_0
  - aws-c-event-stream=0.2.7=h70e1b0c_13
  - aws-c-io=0.10.5=h2fe331c_0
  - aws-checksums=0.1.11=h1e232aa_7
  - aws-sdk-cpp=1.8.186=hb0612c5_3
  - blas=1.0=mkl
  - brotli=1.0.9=h8ffe710_6
  - brotli-bin=1.0.9=h8ffe710_6
  - brotlipy=0.7.0=py37hcc03f2d_1004
  - bzip2=1.0.8=h8ffe710_4
  - c-ares=1.18.1=h8ffe710_0
  - ca-certificates=2022.07.19=haa95532_0
  - certifi=2022.6.15=py37h03978a9_0
  - cffi=1.15.1=py37hd8e9650_0
  - cryptography=37.0.4=py37h65266a2_0
  - cudatoolkit=11.6.0=hc0ea762_10
  - freetype=2.10.4=hd328e21_0
  - gflags=2.2.2=ha925a31_1004
  - glog=0.5.0=h4797de2_0
  - grpc-cpp=1.37.1=h586195c_2
  - idna=3.3=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=haa95532_3556
  - jpeg=9d=h2bbff1b_0
  - krb5=1.19.2=h20d022d_3
  - libbrotlicommon=1.0.9=h8ffe710_6
  - libbrotlidec=1.0.9=h8ffe710_6
  - libbrotlienc=1.0.9=h8ffe710_6
  - libcurl=7.79.1=h789b8ee_1
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.16.0=h7755175_0
  - libssh2=1.10.0=h680486a_2
  - libthrift=0.14.1=h636ae23_2
  - libtiff=4.2.0=hd0e1b90_0
  - libutf8proc=2.6.1=hcb41399_0
  - libuv=1.40.0=he774522_0
  - libwebp=1.2.0=h2bbff1b_0
  - lz4-c=1.9.3=h2bbff1b_1
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py37h2bbff1b_0
  - mkl_fft=1.3.1=py37h277e83a_0
  - mkl_random=1.2.2=py37hf11a4ad_0
  - numpy=1.21.2=py37hfca59bb_0
  - numpy-base=1.21.2=py37h0829f74_0
  - olefile=0.46=py37_0
  - openssl=1.1.1q=h8ffe710_0
  - pandas=1.3.4=py37h9386db6_1
  - pillow=8.4.0=py37hd45dc43_0
  - pip=21.2.4=py37haa95532_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py37h03978a9_5
  - python=3.7.11=h6244533_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.12.1=py3.7_cuda11.6_cudnn8_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=pyhd8ed1ab_0
  - re2=2021.04.01=h0e60522_0
  - requests=2.28.1=pyhd8ed1ab_0
  - setuptools=58.0.4=py37haa95532_0
  - six=1.16.0=pyhd3eb1b0_0
  - snappy=1.1.8=ha925a31_3
  - sqlite=3.36.0=h2bbff1b_0
  - tk=8.6.11=h2bbff1b_0
  - torchaudio=0.12.1=py37_cu116
  - torchvision=0.13.1=py37_cu116
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.0=pyhd3eb1b0_1
  - win_inet_pton=1.1.0=py37h03978a9_4
  - wincertstore=0.2=py37haa95532_2
  - xz=5.2.5=h62dcd97_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - absl-py==1.2.0
    - addict==2.4.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - albumentations==1.2.1
    - appdirs==1.4.4
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - attrs==22.1.0
    - boto3==1.24.47
    - botocore==1.27.47
    - cached-property==1.5.2
    - cachetools==5.2.0
    - charset-normalizer==2.1.0
    - click==8.1.3
    - colorama==0.4.5
    - cycler==0.11.0
    - datasets==2.4.0
    - dill==0.3.5.1
    - docker-pycreds==0.4.0
    - filelock==3.8.0
    - fonttools==4.37.1
    - frozenlist==1.3.1
    - fsspec==2022.7.1
    - gitdb==4.0.10
    - gitpython==3.1.31
    - glob2==0.7
    - google-auth==2.10.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - h5py==3.1.0
    - huggingface-hub==0.9.0
    - imageio==2.21.1
    - importlib-metadata==4.12.0
    - jmespath==1.0.1
    - joblib==1.1.0
    - kiwisolver==1.4.4
    - lmdb==1.4.0
    - lpips==0.1.4
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.5.3
    - mmcv==1.6.1
    - multidict==6.0.2
    - multiprocess==0.70.13
    - natsort==8.1.0
    - networkx==2.6.3
    - oauthlib==3.2.0
    - opencv-python==4.5.2.54
    - orjson==3.7.11
    - packaging==21.3
    - pathtools==0.1.2
    - protobuf==3.19.4
    - psutil==5.9.4
    - pyarrow==9.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==3.0.9
    - pytorch-transformers==1.2.0
    - pywavelets==1.3.0
    - pyyaml==6.0
    - qudida==0.0.4
    - regex==2022.7.25
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rsa==4.9
    - s3transfer==0.6.0
    - sacremoses==0.0.53
    - scikit-image==0.19.3
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - sentencepiece==0.1.97
    - sentry-sdk==1.15.0
    - setproctitle==1.3.2
    - smmap==5.0.0
    - super-image==0.1.6
    - swin-window-process==0.0.0
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - termcolor==2.2.0
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - timm==0.6.12
    - torchinfo==1.7.1
    - torchsummary==1.5.1
    - tqdm==4.64.0
    - wandb==0.13.10
    - werkzeug==2.2.1
    - xxhash==3.0.0
    - yacs==0.1.8
    - yapf==0.32.0
    - yarl==1.8.1
    - zipp==3.8.1
prefix: C:\Users\Yangyi\anaconda3\envs\torch3.7
